server:
  port: 8080

spring:
  profiles:
    active: '@profileActive@'
  druid:
    filters: stat
    maxActive: 20
    minIdle: 5
    initialSize: 1
    maxWait: 60000
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 300000
    validationQuery: select 'x'
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    poolPreparedStatements: true
    maxOpenPreparedStatements: 20

  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

  jackson:
    default-property-inclusion: non_null
  http:
    encoding:
      force: true
      charset: UTF-8
      enabled: true
  freemarker:
    cache: false
    charset: UTF-8
    suffix: .ftl
    enabled: true
    content-type: text/html
    settings:
      number_format: '0.##'

logging:
  level:
    com:
      qnvip:
        iten: warn
      xxl:
        job:
          core: warn
    org:
      springframework:
        web: info
    root: warn